#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x68,0xf3,0x28,0x06,0x4d,0xcf,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x41,0x6d,0xab,0x1d,0x9b,0xef,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
